name: SuggestionsPL
version: '${project.version}'
authors:
  - BopTart
  - itstimetogiveup
main: me.nickpalceski.suggestionspl.SuggestionsPL
api-version: '1.20'
description: "Players can vote on top suggestions to add to the server!"
commands:
  suggestions:
    usage: /<command>
    description: "See the top suggestions."
  addsuggestion:
    usage: /<command>
    description: "Add a suggestion."
    permission: suggestions.add
    permission-message: You do not have permission to add suggestions.
  deletesuggestion:
    usage: /<command>
    description: "Delete a suggestion."
    permission: suggestions.delete
    permission-message: You do not have permission to delete suggestions.
  reloadsuggestions:
    usage: /<command>
    description: "Reloads the suggestions config."
    permission: suggestions.reload
    permission-message: You do not have permission to reload suggestions.
permissions:
  suggestions.add:
    description: Allows the player to add suggestions.
    default: op
  suggestions.delete:
    description: Allows the player to delete suggestions.
    default: op
  suggestions.reload:
    description: Allows the sender to reload suggestions config.
    default: op